"""Constants for the KWB integration."""

DOMAIN = "kwb_heaters"
DEFAULT_NAME = "KWB"
DEFAULT_PORT = 23
# Arbitrary unprivileged default; the serial server must be pointed at it.
DEFAULT_UDP_PORT = 8899
DEFAULT_RAW = False
DEFAULT_PELLET_BULK_DENSITY = 0.65
DEFAULT_BOILER_EFFICIENCY = 95.0
DEFAULT_PELLET_ENERGY = 4.8
CONF_PELLET_PRICE = "pellet_price"
DEFAULT_PELLET_PRICE = 0.0
CONF_RAW = "raw"
CONF_HEATER_MODEL = "heater_model"
CONF_CONTROLLER = "controller"
CONF_NOMINAL_POWER = "nominal_power"
CONF_PELLET_BULK_DENSITY = "pellet_bulk_density"
CONF_BOILER_EFFICIENCY = "boiler_efficiency"
CONF_PELLET_ENERGY = "pellet_energy"

DEFAULT_NOMINAL_POWER = 25.0
PROPERTY_DEFAULTS = {
    CONF_PELLET_PRICE: DEFAULT_PELLET_PRICE,
    CONF_NOMINAL_POWER: DEFAULT_NOMINAL_POWER,
    CONF_BOILER_EFFICIENCY: DEFAULT_BOILER_EFFICIENCY,
    CONF_PELLET_BULK_DENSITY: DEFAULT_PELLET_BULK_DENSITY,
    CONF_PELLET_ENERGY: DEFAULT_PELLET_ENERGY,
}
